### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by supersjimmie** [jkairys/growatt-esp8266#1]
Can you explain how the physical connection is done? Is it just Growatt RX to esp TX and Growatt 
 TX to esp RX or other pins?
And what is your source for those fields/layout ```("Pac1", glueFloat(node.getResponseBuffer(16), node.getResponseBuffer(17)));```? Because I have a 2-MTT growatt and want to know how to find more fields that are required for my inverter.

**Comment by Koenkk** [comment]
@jkairys would indeed be great if you could provide some more details on how to create the setup

**Comment by Mediacj** [comment]
@jkairys thx for sharing your code!

But like the other two I'am looking for a more detailed hardware connection? I have a max3232 together with a nodemcu v3 and get error e2 (time out) my rx and tx are on the default nodemcu rx/tx (I also switched rx/tx) and I use gnd and 3v? Any idea?

Thx in advance!

**Comment by pgielen** [comment]
Maybe here? https://github.com/4-20ma/ModbusMaster

**Comment by supersjimmie** [comment]
@pgielen  yes that's about the bus part, but that does not say anything about what data/fields the growatt sends out.

**Comment by pgielen** [comment]
@supersjimmie Maybe these documents help: 
https://robothuis.nl/wp-content/uploads/2019/09/Growatt-WiFi-Module-Protocol.pdf
https://robothuis.nl/wp-content/uploads/2019/09/Growatt-Server-API-Guide.pdf
https://robothuis.nl/wp-content/uploads/2019/09/Growatt-Server-Open-API-protocol-standards.pdf
https://robothuis.nl/wp-content/uploads/2019/09/GrowattWifiModuleviaRaspberryPitoPVOutputv2.3.pdf

**Comment by nbertram** [comment]
Worth noting the Serial.swap() needs to be removed to use the normal TX/RX pins (eg. on a Wemos D1 like I have)

**Comment by jkairys** [comment]
Hi everyone, first off, my apologies for being completely absent from this thread to date. I never imagined someone would start using this, and last year I had a significant change to my available free time with the arrival of my son! I'd like to tidy this up and see if I can help you out with a schematic and some more info on how I chose those modbus registers. 

To get things started, I've  thrown together an eagle PCB design based on what I _think_ the pinout was for this. My own unit was made of perfboard, hung in a laser cut plywood case... and it recently blew off in the wind, so I've reverse engineered what I can (had to take a small guess at the DB9 pinout but I think it's ok), and will throw it together and update the code when it arrives.

I'll update the repo with a bit more documentation too!

**Comment by Mediacj** [comment]
Great thanks!

**Comment by jkairys** [comment]
Check out 
- the `src/` folder for the library
- the `examples/` folder for a complete example project using the library
- the new `README.md` for pinout
- the `board/` folder for EAGLE project, including schematic and PCB

I also have a few spare PCBs now (min order size was 5) - happy to send to you if you pay shipping.
